/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#ffede6',
        'on-secondary-fixed-variant': '#004c6e',
        'on-primary-fixed-variant': '#003ea8',
        'error': '#ba1a1a',
        'on-surface-variant': '#434655',
        'surface-tint': '#0053db',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#00174b',
        'on-secondary-fixed': '#001e2f',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-bright': '#faf8ff',
        'inverse-surface': '#2e3039',
        'primary': '#004ac6',
        'primary-container': '#2563eb',
        'tertiary-fixed': '#ffdbcd',
        'surface-dim': '#d9d9e5',
        'secondary-fixed': '#c9e6ff',
        'surface-container-low': '#f3f3fe',
        'tertiary-fixed-dim': '#ffb596',
        'on-primary-container': '#eeefff',
        'surface': '#faf8ff',
        'on-background': '#191b23',
        'on-error-container': '#93000a',
        'inverse-primary': '#b4c5ff',
        'on-secondary-container': '#004666',
        'outline-variant': '#c3c6d7',
        'primary-fixed': '#dbe1ff',
        'secondary': '#006591',
        'secondary-fixed-dim': '#89ceff',
        'background': '#faf8ff',
        'on-primary': '#ffffff',
        'tertiary-container': '#bc4800',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'tertiary': '#943700',
        'primary-fixed-dim': '#b4c5ff',
        'surface-variant': '#e1e2ed',
        'surface-container': '#ededf9',
        'outline': '#737686',
        'error-container': '#ffdad6',
        'on-surface': '#191b23',
        'surface-container-highest': '#e1e2ed',
        'inverse-on-surface': '#f0f0fb',
        'on-tertiary-fixed': '#360f00',
        'secondary-container': '#39b8fd',
        'surface-container-high': '#e7e7f3',
        'on-tertiary': '#ffffff'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        md: '16px',
        sm: '8px',
        base: '8px',
        xs: '4px',
        xxl: '48px',
        lg: '24px',
        xl: '32px',
        xxxl: '64px'
      },
      fontFamily: {
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'label-md': ['Inter']
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }]
      }
    },
  },
  plugins: [],
}
