import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type Language = 'en' | 'ja' | 'vi'

type TranslationValue = string | TranslationTree
type TranslationTree = {
  [key: string]: TranslationValue
}

const LANGUAGE_STORAGE_KEY = 'medprecision.language'

export const languages: Array<{ code: Language; label: string; shortLabel: string }> = [
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'ja', label: '日本語', shortLabel: 'JA' },
  { code: 'vi', label: 'Tiếng Việt', shortLabel: 'VI' },
]

const translations: Record<Language, TranslationTree> = {
  en: {
    common: {
      details: 'Details',
      book: 'Book',
      bookNow: 'Book now',
      bookThisDoctor: 'Book this doctor',
      bookThisDepartment: 'Book this department',
      yearsExperience: '{{years}} years of experience',
      consultationFee: 'Consultation fee: {{fee}}',
      processing: 'Processing...',
      showingRange: 'Showing {{first}}-{{last}} of {{total}} {{itemLabel}}',
      previous: 'Previous',
      next: 'Next',
      nearest: 'Nearest: {{time}}',
      appointments: 'Book appointment',
      doctor: 'doctor',
      doctors: 'doctors',
      login: 'Log in',
      viewAll: 'View all',
    },
    nav: {
      home: 'Home',
      doctors: 'Find doctors',
      departments: 'Departments',
      symptoms: 'Check symptoms',
    },
    account: {
      doctorSchedule: 'My schedule',
      patientAppointments: 'My appointments',
      profile: 'Profile',
      logout: 'Log out',
      menu: 'Account menu',
    },
    preferences: {
      language: 'Language',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
    },
    auth: {
      emailDivider: 'OR CONTINUE WITH EMAIL',
      loginHeroTitle: 'Manage healthcare on one secure platform.',
      loginHeroDescription: 'Access your profile, book appointments, and connect with verified medical specialists.',
      signupHeroTitle: 'Start your proactive healthcare journey.',
      signupHeroDescription: 'Create an account to save appointments, manage your profile, and follow matching specialists.',
      welcomeBack: 'Welcome back',
      loginDescription: 'Enter your details to access the MedPrecision portal.',
      emailLabel: 'Email address',
      passwordLabel: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      loginButton: 'Log in',
      noAccount: 'No account yet?',
      signupNow: 'Sign up now',
      createAccount: 'Create account',
      signupDescription: 'Create a new account to start using the platform.',
      fullNameLabel: 'Full name',
      phoneLabel: 'Phone number',
      confirmPasswordLabel: 'Confirm password',
      acceptTerms: 'I agree to the terms',
      signupButton: 'Sign up',
      hasAccount: 'Already have an account?',
      validationEmailPassword: 'Please enter email and password.',
      loginFailed: 'Login failed.',
      forgotMissingEmail: 'Please enter your email to receive the code.',
      forgotSent: 'A verification code has been sent. Please check your email and enter the code to reset your password.',
      requestFailed: 'Request failed.',
      resetInvalidEmail: 'The reset email is invalid.',
      resetMissingCode: 'Please enter the verification code.',
      resetMissingPassword: 'Please enter and confirm your new password.',
      passwordMismatch: 'The confirmation password does not match.',
      resetSuccess: 'Password reset successfully. You can now log in with your new password.',
      resetFailed: 'Could not reset password.',
      signupEmailPasswordRequired: 'Email and password are required.',
      termsRequired: 'You need to agree to the terms before signing up.',
      signupSuccess: 'Registration successful. You can log in now.',
      signupFailed: 'Registration failed.',
      closePopup: 'Close popup',
      close: 'Close',
      forgotEyebrow: 'Forgot password',
      forgotTitle: 'Get verification code',
      forgotDescription: 'Enter the email you used to register. The system will send a 6-digit verification code to this address to reset your password.',
      cancel: 'Cancel',
      sendCode: 'Send verification code',
      resetEyebrow: 'Reset password',
      resetTitle: 'Create a new password',
      resetDescription: 'Enter the verification code sent to your email and create a new password to recover your account.',
      yourEmailPlaceholder: 'Your email',
      codeLabel: 'Verification code',
      codePlaceholder: 'Enter 6-digit code',
      newPasswordLabel: 'New password',
      newPasswordPlaceholder: 'Enter new password',
      confirmPasswordPlaceholder: 'Re-enter password',
      confirm: 'Confirm',
      googleMissingCredential: 'Google credential is missing.',
      googleLoginFailed: 'Google login failed.',
    },
    home: {
      hero: {
        badge: 'Precise and trusted medical care',
        titleStart: 'Find the right doctor,',
        titleHighlight: 'right on time.',
        description: 'Connect with the right specialist based on your symptoms, department, and specific care needs.',
        imageAlt: 'Professional doctor at MedPrecision',
        verified: 'Verified specialists',
        doctorImageAlt: 'Doctor photo',
        searchAria: 'Search',
        searchButton: 'Find matching doctors',
      },
      featuredDoctors: {
        title: 'Featured specialists',
        backendError: 'Could not connect to the backend, so doctor data is not available yet.',
        loading: 'Loading doctors...',
        empty: 'No doctor data is available yet.',
      },
      departments: {
        title: 'Specialty departments',
        description: 'Active departments in the system.',
        loading: 'Loading departments...',
        backendError: 'Could not connect to the backend, so department data is not available yet.',
        previousSlide: 'View previous department slide',
        nextSlide: 'View next department slide',
        goToSlide: 'Go to department slide {{number}}',
      },
      testimonials: {
        fallbackDoctor: 'doctor',
        meta: 'Review for {{doctorName}}',
        title: 'Patient reviews',
        description: 'Shared experiences after finding doctors, booking visits, and following consultations in the system.',
        backendError: 'Could not load reviews from the backend.',
        empty: 'No patient reviews are available yet.',
      },
    },
    symptomChecker: {
      searchAria: 'Symptoms',
      searchPlaceholder: 'Enter symptoms, for example: chest pain, shortness of breath...',
      analyze: 'Analyze',
      suggestedDoctors: 'Suggested doctors',
      suggestedDepartments: 'Suggested departments',
      loadingDoctors: 'Loading doctor data from the backend...',
      doctorsBackendError: 'Could not connect to the backend, so doctor data is not available yet.',
      noDoctorData: 'No doctor data is available yet.',
      noDepartmentData: 'No suggested department data is available yet.',
      preVisitNote: 'Before your visit',
      matchingSymptoms: 'Matches: {{symptoms}}',
      fallbackDepartmentDescription: 'A suitable department for the symptoms you entered.',
      activeDepartmentFallback: 'This department is accepting appointments.',
    },
    aiChat: {
      emergency: 'Danger signs detected. Consider seeking emergency care immediately.',
      relatedDocuments: 'Related documents',
      matchingDoctors: 'Matching doctors',
      suggestedDepartments: 'Suggested departments',
      title: 'AI assistant',
      subtitle: 'Suggested departments for reference',
      defaultMessage: 'Hello, I am the AI assistant. What symptoms are you experiencing? I can suggest a suitable department for booking.',
      sessionExpired: 'Your session has expired. Please log in again.',
      unavailable: 'The AI assistant is unavailable right now.',
    },
    doctorDetail: {
      back: 'Back to doctor list',
      loading: 'Loading doctor details...',
      errorTitle: 'Could not load doctor details.',
      errorDescription: 'Please check the link or try again later.',
      fallbackDescription: 'Professional information is being updated.',
      experience: 'Experience',
      fee: 'Consultation fee',
      status: 'Status',
      reviews: 'Reviews',
      yearsShort: '{{years}} years',
      updating: 'Updating',
      acceptingAppointments: 'Accepting appointments',
      paused: 'Paused',
      noReviews: 'No reviews yet',
      reviewCount: '{{count}} reviews',
      bookAppointment: 'Book appointment',
      biographyTab: 'Biography',
      educationTab: 'Education',
      biographyTitle: 'Professional biography',
      educationTitle: 'Education',
      patientReviews: 'Patient reviews',
      loginToReview: 'Log in to review this doctor.',
      yourReview: 'Your review',
      selectStars: 'Choose a star rating',
      commentPlaceholder: 'Share your experience (optional)',
      submitReview: 'Submit review',
      updateReview: 'Update review',
      deleteReview: 'Delete',
      loadingReviews: 'Loading reviews...',
      loadingReviewSummary: 'Loading review overview...',
      loadMore: 'Load more',
      starLabel: '{{count}} stars',
      specialtyFallback: 'Specialty',
      ratingSelectWarning: 'Please choose a star rating before submitting your review.',
      ratingAppointmentRequired: 'You need to complete an appointment before reviewing.',
      ratingSubmitSuccess: 'Your review has been submitted.',
      ratingSubmitError: 'Could not submit review.',
      ratingDeleteSuccess: 'Your review has been deleted.',
      ratingDeleteError: 'Could not delete review.',
    },
    doctorsPage: {
      unassignedDepartment: 'Unassigned department',
      experience: {
        all: 'All',
        from5: 'From 5 years',
        from10: 'From 10 years',
        from15: 'From 15 years',
      },
      fee: {
        all: 'All',
        under300: 'Under 300,000 VND',
        between300And350: '300,000 VND - 350,000 VND',
        over350: 'Over 350,000 VND',
      },
      eyebrow: 'Specialist directory',
      title: 'All doctors',
      description: 'Search by symptom, doctor name, or department. Use quick filters to narrow results by specialty, consultation fee, and experience.',
      searchLabel: 'Search doctors',
      searchPlaceholder: 'Enter a doctor name, department, or specialty...',
      departmentLabel: 'Department',
      allDepartments: 'All departments',
      feeLabel: 'Consultation fee',
      experienceLabel: 'Experience',
      resultCount: '{{visible}}/{{total}} doctors',
      clearFilters: 'Clear filters',
      loading: 'Loading doctors...',
      error: 'Could not load doctors.',
      emptyTitle: 'No matching doctors found',
      emptyDescription: 'Try another symptom or clear the search filters.',
    },
    departmentsPage: {
      eyebrow: 'Specialty departments',
      title: 'Department list',
      description: 'Browse all active departments and choose the right doctor for your care needs.',
      searchLabel: 'Search departments',
      searchPlaceholder: 'Example: Cardiology, Dermatology, Pulmonology...',
      loading: 'Loading departments...',
      error: 'Could not load departments.',
      emptyTitle: 'No matching departments found',
      emptyDescription: 'Try another keyword or clear the search field.',
      fallbackDescription: 'This department is accepting appointments in the system.',
      viewDetails: 'View department details',
      itemLabel: 'departments',
    },
    departmentDetail: {
      back: 'Back to department list',
      loading: 'Loading department details...',
      error: 'Could not load department details.',
      infoEyebrow: 'Department information',
      fallbackDescription: 'This department is accepting appointments and consultations in the system.',
      statusTitle: 'Status',
      activeStatus: 'Active and accepting appointments.',
      inactiveStatus: 'Currently not accepting appointments.',
      doctorCount: '{{count}} assigned doctors',
      overviewTitle: 'Overview',
      overviewFallback: 'This department accepts, examines, and treats suitable healthcare needs in the system.',
      teamTitle: 'Specialist team',
      teamText: 'The department is operated by doctors active in the system, with professional profiles and updated schedules for easier patient selection.',
      bookingTitle: 'Booking',
      bookingText: 'Patients can choose a doctor in this department, view available slots by date, and send appointment requests directly in the system.',
      doctorsEyebrow: 'Assigned doctors',
      viewDirectory: 'View in directory',
      emptyTitle: 'No doctors are assigned to this department yet',
      emptyDescription: 'Please check again after the system updates more doctor profiles.',
    },
    payment: {
      title: 'Appointment payment',
      amount: 'Amount',
      paymentCode: 'Payment code',
      appointmentCode: 'Appointment code',
      transferContent: 'Transfer content',
      pending: 'Awaiting payment',
      paid: 'Paid',
      failed: 'Payment failed',
      cancelled: 'Cancelled',
      downloadInvoice: 'Download PDF invoice',
      downloading: 'Downloading...',
      successToast: 'Payment successful. The appointment has been confirmed.',
      statusError: 'Could not load payment status.',
      loadingQr: 'Loading payment QR code...',
      invoiceError: 'Could not load invoice.',
      successEyebrow: 'Payment successful',
      successTitle: 'Appointment confirmed',
      doctorLabel: 'Doctor',
      timeLabel: 'Appointment time',
      fallbackDoctor: 'Doctor',
      updating: 'Updating',
    },
  },
  ja: {
    common: {
      details: '詳細',
      book: '予約',
      bookNow: '今すぐ予約',
      bookThisDoctor: 'この医師を予約',
      bookThisDepartment: 'この診療科を予約',
      yearsExperience: '{{years}}年の経験',
      consultationFee: '相談料: {{fee}}',
      processing: '処理中...',
      showingRange: '{{total}}件中 {{first}}-{{last}}件の{{itemLabel}}を表示',
      previous: '前へ',
      next: '次へ',
      nearest: '最短: {{time}}',
      appointments: '予約する',
      doctor: '医師',
      doctors: '医師',
      login: 'ログイン',
      viewAll: 'すべて見る',
    },
    nav: {
      home: 'ホーム',
      doctors: '医師を探す',
      departments: '診療科',
      symptoms: '症状チェック',
    },
    account: {
      doctorSchedule: '自分の診療予定',
      patientAppointments: '自分の予約',
      profile: 'プロフィール',
      logout: 'ログアウト',
      menu: 'アカウントメニュー',
    },
    preferences: {
      language: '言語',
      theme: 'テーマ',
      light: 'ライト',
      dark: 'ダーク',
    },
    auth: {
      emailDivider: 'メールで続行',
      loginHeroTitle: '安全なプラットフォームで医療を管理できます。',
      loginHeroDescription: 'プロフィール、予約、認証済み医療専門家との接続を利用できます。',
      signupHeroTitle: '主体的なヘルスケアを始めましょう。',
      signupHeroDescription: 'アカウントを作成して予約を保存し、プロフィールを管理し、適切な専門家を確認できます。',
      welcomeBack: 'おかえりなさい',
      loginDescription: 'MedPrecisionポータルにアクセスするための情報を入力してください。',
      emailLabel: 'メールアドレス',
      passwordLabel: 'パスワード',
      rememberMe: 'ログイン状態を保持',
      forgotPassword: 'パスワードをお忘れですか？',
      loginButton: 'ログイン',
      noAccount: 'アカウントをお持ちでないですか？',
      signupNow: '今すぐ登録',
      createAccount: 'アカウント作成',
      signupDescription: 'プラットフォームの利用を開始するために新しいアカウントを作成します。',
      fullNameLabel: '氏名',
      phoneLabel: '電話番号',
      confirmPasswordLabel: 'パスワード確認',
      acceptTerms: '利用規約に同意します',
      signupButton: '登録',
      hasAccount: 'すでにアカウントをお持ちですか？',
      validationEmailPassword: 'メールアドレスとパスワードを入力してください。',
      loginFailed: 'ログインに失敗しました。',
      forgotMissingEmail: 'コードを受け取るメールアドレスを入力してください。',
      forgotSent: '確認コードを送信しました。メールを確認し、コードを入力してパスワードをリセットしてください。',
      requestFailed: 'リクエストに失敗しました。',
      resetInvalidEmail: 'リセット用メールアドレスが無効です。',
      resetMissingCode: '確認コードを入力してください。',
      resetMissingPassword: '新しいパスワードと確認を入力してください。',
      passwordMismatch: '確認用パスワードが一致しません。',
      resetSuccess: 'パスワードをリセットしました。新しいパスワードでログインできます。',
      resetFailed: 'パスワードをリセットできませんでした。',
      signupEmailPasswordRequired: 'メールアドレスとパスワードは必須です。',
      termsRequired: '登録前に利用規約への同意が必要です。',
      signupSuccess: '登録が完了しました。ログインできます。',
      signupFailed: '登録に失敗しました。',
      closePopup: 'ポップアップを閉じる',
      close: '閉じる',
      forgotEyebrow: 'パスワードを忘れた場合',
      forgotTitle: '確認コードを受け取る',
      forgotDescription: '登録時に使用したメールアドレスを入力してください。パスワードをリセットするための6桁の確認コードを送信します。',
      cancel: 'キャンセル',
      sendCode: '確認コードを送信',
      resetEyebrow: 'パスワードリセット',
      resetTitle: '新しいパスワードを作成',
      resetDescription: 'メールに送信された確認コードを入力し、新しいパスワードを作成してアカウントを復旧します。',
      yourEmailPlaceholder: 'あなたのメール',
      codeLabel: '確認コード',
      codePlaceholder: '6桁のコードを入力',
      newPasswordLabel: '新しいパスワード',
      newPasswordPlaceholder: '新しいパスワードを入力',
      confirmPasswordPlaceholder: 'パスワードを再入力',
      confirm: '確認',
      googleMissingCredential: 'Google認証情報がありません。',
      googleLoginFailed: 'Googleログインに失敗しました。',
    },
    home: {
      hero: {
        badge: '正確で信頼できる医療',
        titleStart: '最適な医師を、',
        titleHighlight: '最適なタイミングで。',
        description: '症状、診療科、具体的な受診ニーズに基づいて適切な専門医につなげます。',
        imageAlt: 'MedPrecisionの専門医',
        verified: '認証済みの専門家',
        doctorImageAlt: '医師の写真',
        searchAria: '検索',
        searchButton: '適切な医師を探す',
      },
      featuredDoctors: {
        title: '注目の専門家',
        backendError: 'バックエンドに接続できないため、医師データを表示できません。',
        loading: '医師一覧を読み込み中...',
        empty: '医師データはまだありません。',
      },
      departments: {
        title: '専門診療科',
        description: 'システム上で有効な診療科の一覧です。',
        loading: '診療科一覧を読み込み中...',
        backendError: 'バックエンドに接続できないため、診療科データを表示できません。',
        previousSlide: '前の診療科スライドを表示',
        nextSlide: '次の診療科スライドを表示',
        goToSlide: '診療科スライド {{number}} へ移動',
      },
      testimonials: {
        fallbackDoctor: '医師',
        meta: '{{doctorName}} への評価',
        title: '患者の評価',
        description: '医師の検索、予約、システム上での相談後の体験です。',
        backendError: 'バックエンドから評価を読み込めませんでした。',
        empty: '患者の評価はまだありません。',
      },
    },
    symptomChecker: {
      searchAria: '症状',
      searchPlaceholder: '症状を入力してください。例: 胸の痛み、息切れ...',
      analyze: '分析',
      suggestedDoctors: 'おすすめ医師',
      suggestedDepartments: 'おすすめ診療科',
      loadingDoctors: 'バックエンドから医師データを読み込み中...',
      doctorsBackendError: 'バックエンドに接続できないため、医師データを表示できません。',
      noDoctorData: '医師データはまだありません。',
      noDepartmentData: 'おすすめ診療科データはまだありません。',
      preVisitNote: '受診前の注意',
      matchingSymptoms: '一致する症状: {{symptoms}}',
      fallbackDepartmentDescription: '入力した症状に適した診療科です。',
      activeDepartmentFallback: 'この診療科は予約を受け付けています。',
    },
    aiChat: {
      emergency: '危険な兆候があります。すぐに救急受診を検討してください。',
      relatedDocuments: '関連資料',
      matchingDoctors: '適した医師',
      suggestedDepartments: 'おすすめ診療科',
      title: 'AIアシスタント',
      subtitle: '参考となる診療科の提案',
      defaultMessage: 'こんにちは、AIアシスタントです。どのような症状がありますか？予約に適した診療科を提案できます。',
      sessionExpired: 'セッションの有効期限が切れました。再度ログインしてください。',
      unavailable: '現在AIアシスタントを利用できません。',
    },
    doctorDetail: {
      back: '医師一覧に戻る',
      loading: '医師情報を読み込み中...',
      errorTitle: '医師の詳細情報を読み込めません。',
      errorDescription: 'リンクを確認するか、後でもう一度お試しください。',
      fallbackDescription: '専門情報は更新中です。',
      experience: '経験',
      fee: '相談料',
      status: 'ステータス',
      reviews: '評価',
      yearsShort: '{{years}}年',
      updating: '更新中',
      acceptingAppointments: '予約受付中',
      paused: '一時停止',
      noReviews: 'まだ評価はありません',
      reviewCount: '{{count}}件の評価',
      bookAppointment: '診療予約',
      biographyTab: '経歴',
      educationTab: '研修',
      biographyTitle: '専門経歴',
      educationTitle: '研修',
      patientReviews: '患者からの評価',
      loginToReview: '医師を評価するにはログインしてください。',
      yourReview: 'あなたの評価',
      selectStars: '星の数を選択',
      commentPlaceholder: '体験を共有してください（任意）',
      submitReview: '評価を送信',
      updateReview: '評価を更新',
      deleteReview: '削除',
      loadingReviews: '評価を読み込み中...',
      loadingReviewSummary: '評価概要を読み込み中...',
      loadMore: 'さらに読み込む',
      starLabel: '{{count}}つ星',
      specialtyFallback: '専門科',
      ratingSelectWarning: '評価を送信する前に星の数を選択してください。',
      ratingAppointmentRequired: '評価するには診療予約を完了する必要があります。',
      ratingSubmitSuccess: '評価を送信しました。',
      ratingSubmitError: '評価を送信できませんでした。',
      ratingDeleteSuccess: '評価を削除しました。',
      ratingDeleteError: '評価を削除できませんでした。',
    },
    doctorsPage: {
      unassignedDepartment: '未割り当ての診療科',
      experience: {
        all: 'すべて',
        from5: '5年以上',
        from10: '10年以上',
        from15: '15年以上',
      },
      fee: {
        all: 'すべて',
        under300: '300,000 VND未満',
        between300And350: '300,000 VND - 350,000 VND',
        over350: '350,000 VND超',
      },
      eyebrow: '専門家ディレクトリ',
      title: 'すべての医師',
      description: '症状、医師名、診療科で検索できます。専門、相談料、経験で絞り込めます。',
      searchLabel: '医師を検索',
      searchPlaceholder: '医師名、診療科、専門分野を入力...',
      departmentLabel: '診療科',
      allDepartments: 'すべての診療科',
      feeLabel: '相談料',
      experienceLabel: '経験',
      resultCount: '{{visible}}/{{total}} 医師',
      clearFilters: 'フィルターをクリア',
      loading: '医師一覧を読み込み中...',
      error: '医師一覧を読み込めません。',
      emptyTitle: '条件に合う医師が見つかりません',
      emptyDescription: '別の症状を入力するか、検索フィルターをクリアしてください。',
    },
    departmentsPage: {
      eyebrow: '専門診療科',
      title: '診療科一覧',
      description: '有効な診療科を確認し、ニーズに合う医師を選べます。',
      searchLabel: '診療科を検索',
      searchPlaceholder: '例: 循環器、皮膚科、呼吸器...',
      loading: '診療科一覧を読み込み中...',
      error: '診療科一覧を読み込めません。',
      emptyTitle: '条件に合う診療科が見つかりません',
      emptyDescription: '別のキーワードを入力するか、検索内容をクリアしてください。',
      fallbackDescription: 'この診療科はシステム上で予約を受け付けています。',
      viewDetails: '診療科詳細を見る',
      itemLabel: '診療科',
    },
    departmentDetail: {
      back: '診療科一覧に戻る',
      loading: '診療科情報を読み込み中...',
      error: '診療科情報を読み込めません。',
      infoEyebrow: '診療科情報',
      fallbackDescription: 'この診療科はシステム上で予約と相談を受け付けています。',
      statusTitle: 'ステータス',
      activeStatus: '稼働中で予約を受け付けています。',
      inactiveStatus: '現在予約を受け付けていません。',
      doctorCount: '{{count}} 名の所属医師',
      overviewTitle: '概要',
      overviewFallback: 'この診療科はシステム上で適切な医療ニーズの受付、診察、治療を行います。',
      teamTitle: '専門チーム',
      teamText: 'この診療科はシステム上で活動中の医師により運営され、患者が選びやすいよう専門プロフィールと診療予定が更新されます。',
      bookingTitle: '予約',
      bookingText: '患者は診療科所属の医師を選び、日付ごとの空き枠を確認して、システム上で予約リクエストを送信できます。',
      doctorsEyebrow: '所属医師',
      viewDirectory: 'ディレクトリで見る',
      emptyTitle: 'この診療科にはまだ所属医師がいません',
      emptyDescription: '医師プロフィールが追加更新された後にもう一度確認してください。',
    },
    payment: {
      title: '診療予約の支払い',
      amount: '金額',
      paymentCode: '支払いコード',
      appointmentCode: '予約コード',
      transferContent: '振込内容',
      pending: '支払い待ち',
      paid: '支払い済み',
      failed: '支払い失敗',
      cancelled: 'キャンセル済み',
      downloadInvoice: 'PDF請求書をダウンロード',
      downloading: 'ダウンロード中...',
      successToast: '支払いが完了しました。予約が確定しました。',
      statusError: '支払い状況を読み込めません。',
      loadingQr: '支払い用QRコードを読み込み中...',
      invoiceError: '請求書を読み込めません。',
      successEyebrow: '支払い完了',
      successTitle: '予約が確定しました',
      doctorLabel: '医師',
      timeLabel: '診療時間',
      fallbackDoctor: '医師',
      updating: '更新中',
    },
  },
  vi: {
    common: {
      details: 'Chi tiết',
      book: 'Đặt lịch',
      bookNow: 'Đặt lịch ngay',
      bookThisDoctor: 'Đặt lịch bác sĩ này',
      bookThisDepartment: 'Đặt lịch khoa này',
      yearsExperience: '{{years}} năm kinh nghiệm',
      consultationFee: 'Phí tư vấn: {{fee}}',
      processing: 'Đang xử lý...',
      showingRange: 'Hiển thị {{first}}-{{last}} trong {{total}} {{itemLabel}}',
      previous: 'Trước',
      next: 'Sau',
      nearest: 'Gần nhất: {{time}}',
      appointments: 'Đặt lịch hẹn',
      doctor: 'bác sĩ',
      doctors: 'bác sĩ',
      login: 'Đăng nhập',
      viewAll: 'Xem tất cả',
    },
    nav: {
      home: 'Trang chủ',
      doctors: 'Tìm bác sĩ',
      departments: 'Khoa',
      symptoms: 'Kiểm tra triệu chứng',
    },
    account: {
      doctorSchedule: 'Lịch khám của tôi',
      patientAppointments: 'Lịch hẹn của tôi',
      profile: 'Hồ sơ cá nhân',
      logout: 'Đăng xuất',
      menu: 'Menu tài khoản',
    },
    preferences: {
      language: 'Ngôn ngữ',
      theme: 'Giao diện',
      light: 'Sáng',
      dark: 'Tối',
    },
    auth: {
      emailDivider: 'HOẶC TIẾP TỤC VỚI EMAIL',
      loginHeroTitle: 'Quản lý chăm sóc sức khỏe trên một nền tảng an toàn.',
      loginHeroDescription: 'Truy cập hồ sơ cá nhân, đặt lịch và kết nối với chuyên gia y tế đã xác thực.',
      signupHeroTitle: 'Bắt đầu hành trình chăm sóc sức khỏe chủ động.',
      signupHeroDescription: 'Tạo tài khoản để lưu lịch hẹn, quản lý hồ sơ và theo dõi các chuyên gia phù hợp.',
      welcomeBack: 'Chào mừng trở lại',
      loginDescription: 'Nhập thông tin để truy cập cổng thông tin MedPrecision.',
      emailLabel: 'Địa chỉ email',
      passwordLabel: 'Mật khẩu',
      rememberMe: 'Ghi nhớ đăng nhập',
      forgotPassword: 'Quên mật khẩu?',
      loginButton: 'Đăng nhập',
      noAccount: 'Chưa có tài khoản?',
      signupNow: 'Đăng ký ngay',
      createAccount: 'Tạo tài khoản',
      signupDescription: 'Tạo tài khoản mới để bắt đầu sử dụng nền tảng.',
      fullNameLabel: 'Họ và tên',
      phoneLabel: 'Số điện thoại',
      confirmPasswordLabel: 'Xác nhận mật khẩu',
      acceptTerms: 'Tôi đồng ý với điều khoản',
      signupButton: 'Đăng ký',
      hasAccount: 'Đã có tài khoản?',
      validationEmailPassword: 'Vui lòng nhập email và mật khẩu.',
      loginFailed: 'Đăng nhập không thành công.',
      forgotMissingEmail: 'Vui lòng nhập email để nhận mã xác thực.',
      forgotSent: 'Mã xác thực đã gửi. Vui lòng kiểm tra email và nhập mã để đặt lại mật khẩu.',
      requestFailed: 'Yêu cầu không thành công.',
      resetInvalidEmail: 'Email đặt lại mật khẩu không hợp lệ.',
      resetMissingCode: 'Vui lòng nhập mã xác thực.',
      resetMissingPassword: 'Vui lòng nhập mật khẩu mới và xác nhận.',
      passwordMismatch: 'Mật khẩu xác nhận không khớp.',
      resetSuccess: 'Đặt lại mật khẩu thành công. Bạn có thể đăng nhập bằng mật khẩu mới.',
      resetFailed: 'Không thể đặt lại mật khẩu.',
      signupEmailPasswordRequired: 'Email và mật khẩu là bắt buộc.',
      termsRequired: 'Bạn cần đồng ý với điều khoản trước khi đăng ký.',
      signupSuccess: 'Đăng ký thành công. Bạn có thể đăng nhập ngay.',
      signupFailed: 'Đăng ký không thành công.',
      closePopup: 'Đóng popup',
      close: 'Đóng',
      forgotEyebrow: 'Quên mật khẩu',
      forgotTitle: 'Nhận mã xác thực',
      forgotDescription: 'Nhập email bạn đã dùng để đăng ký. Hệ thống sẽ gửi mã xác thực 6 chữ số vào địa chỉ này để đặt lại mật khẩu.',
      cancel: 'Hủy',
      sendCode: 'Gửi mã xác thực',
      resetEyebrow: 'Đặt lại mật khẩu',
      resetTitle: 'Tạo mật khẩu mới',
      resetDescription: 'Nhập mã xác thực đã gửi đến email của bạn và tạo mật khẩu mới để hoàn tất khôi phục tài khoản.',
      yourEmailPlaceholder: 'Email của bạn',
      codeLabel: 'Mã xác thực',
      codePlaceholder: 'Nhập mã 6 chữ số',
      newPasswordLabel: 'Mật khẩu mới',
      newPasswordPlaceholder: 'Nhập mật khẩu mới',
      confirmPasswordPlaceholder: 'Nhập lại mật khẩu',
      confirm: 'Xác nhận',
      googleMissingCredential: 'Thiếu thông tin xác thực Google.',
      googleLoginFailed: 'Đăng nhập Google không thành công.',
    },
    home: {
      hero: {
        badge: 'Y khoa chính xác và tin cậy',
        titleStart: 'Tìm đúng bác sĩ,',
        titleHighlight: 'đúng lúc.',
        description: 'Kết nối với chuyên gia phù hợp dựa trên triệu chứng, chuyên khoa và nhu cầu thăm khám cụ thể của bạn.',
        imageAlt: 'Bác sĩ chuyên nghiệp tại MedPrecision',
        verified: 'Chuyên gia đã xác thực',
        doctorImageAlt: 'Ảnh bác sĩ',
        searchAria: 'Tìm kiếm',
        searchButton: 'Tìm bác sĩ phù hợp',
      },
      featuredDoctors: {
        title: 'Chuyên gia nổi bật',
        backendError: 'Chưa kết nối được backend nên chưa có dữ liệu bác sĩ để hiển thị.',
        loading: 'Đang tải danh sách bác sĩ...',
        empty: 'Chưa có dữ liệu bác sĩ.',
      },
      departments: {
        title: 'Khoa chuyên môn',
        description: 'Danh mục khoa đang hoạt động trong hệ thống.',
        loading: 'Đang tải danh sách khoa...',
        backendError: 'Chưa kết nối được backend nên chưa có dữ liệu khoa để hiển thị.',
        previousSlide: 'Xem slide khoa trước',
        nextSlide: 'Xem slide khoa tiếp theo',
        goToSlide: 'Đi tới slide khoa {{number}}',
      },
      testimonials: {
        fallbackDoctor: 'bác sĩ',
        meta: 'Đánh giá cho {{doctorName}}',
        title: 'Đánh giá từ bệnh nhân',
        description: 'Những chia sẻ sau khi tìm bác sĩ, đặt lịch và theo dõi tư vấn trên hệ thống.',
        backendError: 'Chưa tải được đánh giá từ backend.',
        empty: 'Chưa có đánh giá bệnh nhân để hiển thị.',
      },
    },
    symptomChecker: {
      searchAria: 'Triệu chứng',
      searchPlaceholder: 'Nhập triệu chứng, ví dụ: đau ngực, khó thở...',
      analyze: 'Phân tích',
      suggestedDoctors: 'Bác sĩ đề xuất',
      suggestedDepartments: 'Các khoa gợi ý',
      loadingDoctors: 'Đang tải dữ liệu bác sĩ từ backend...',
      doctorsBackendError: 'Chưa kết nối được backend nên chưa có dữ liệu bác sĩ để hiển thị.',
      noDoctorData: 'Chưa có dữ liệu bác sĩ.',
      noDepartmentData: 'Chưa có dữ liệu khoa gợi ý.',
      preVisitNote: 'Lưu ý trước khi khám',
      matchingSymptoms: 'Phù hợp với: {{symptoms}}',
      fallbackDepartmentDescription: 'Khoa phù hợp với triệu chứng bạn đã nhập.',
      activeDepartmentFallback: 'Khoa đang tiếp nhận lịch khám.',
    },
    aiChat: {
      emergency: 'Dấu hiệu nguy hiểm, hãy cân nhắc đi cấp cứu ngay.',
      relatedDocuments: 'Tài liệu liên quan',
      matchingDoctors: 'Bác sĩ phù hợp',
      suggestedDepartments: 'Khoa đề xuất',
      title: 'Trợ lý AI',
      subtitle: 'Gợi ý khoa khám tham khảo',
      defaultMessage: 'Xin chào, tôi là trợ lý AI. Bạn đang gặp triệu chứng gì? Tôi có thể gợi ý khoa phù hợp để bạn đặt lịch khám.',
      sessionExpired: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
      unavailable: 'Không thể gọi trợ lý AI lúc này.',
    },
    doctorDetail: {
      back: 'Quay lại danh sách bác sĩ',
      loading: 'Đang tải thông tin bác sĩ...',
      errorTitle: 'Không thể tải thông tin chi tiết bác sĩ.',
      errorDescription: 'Vui lòng kiểm tra lại đường dẫn hoặc thử lại sau.',
      fallbackDescription: 'Thông tin chuyên môn đang được cập nhật.',
      experience: 'Kinh nghiệm',
      fee: 'Phí tư vấn',
      status: 'Trạng thái',
      reviews: 'Đánh giá',
      yearsShort: '{{years}} năm',
      updating: 'Đang cập nhật',
      acceptingAppointments: 'Đang nhận lịch',
      paused: 'Tạm ngưng',
      noReviews: 'Chưa có',
      reviewCount: '{{count}} lượt đánh giá',
      bookAppointment: 'Đặt lịch khám',
      biographyTab: 'Tiểu sử',
      educationTab: 'Đào tạo',
      biographyTitle: 'Tiểu sử chuyên môn',
      educationTitle: 'Đào tạo',
      patientReviews: 'Đánh giá từ bệnh nhân',
      loginToReview: 'Đăng nhập để đánh giá bác sĩ.',
      yourReview: 'Đánh giá của bạn',
      selectStars: 'Chọn số sao',
      commentPlaceholder: 'Chia sẻ trải nghiệm của bạn (không bắt buộc)',
      submitReview: 'Gửi đánh giá',
      updateReview: 'Cập nhật đánh giá',
      deleteReview: 'Xóa',
      loadingReviews: 'Đang tải đánh giá...',
      loadingReviewSummary: 'Đang tải tổng quan đánh giá...',
      loadMore: 'Tải thêm',
      starLabel: '{{count}} sao',
      specialtyFallback: 'Chuyên khoa',
      ratingSelectWarning: 'Vui lòng chọn số sao trước khi gửi đánh giá.',
      ratingAppointmentRequired: 'Bạn cần hoàn thành lịch hẹn trước khi đánh giá.',
      ratingSubmitSuccess: 'Đánh giá đã được gửi thành công.',
      ratingSubmitError: 'Không thể gửi đánh giá.',
      ratingDeleteSuccess: 'Đánh giá đã được xóa.',
      ratingDeleteError: 'Không thể xóa đánh giá.',
    },
    doctorsPage: {
      unassignedDepartment: 'Chưa phân khoa',
      experience: {
        all: 'Tất cả',
        from5: 'Từ 5 năm',
        from10: 'Từ 10 năm',
        from15: 'Từ 15 năm',
      },
      fee: {
        all: 'Tất cả',
        under300: 'Dưới 300.000đ',
        between300And350: '300.000đ - 350.000đ',
        over350: 'Trên 350.000đ',
      },
      eyebrow: 'Danh bạ chuyên gia',
      title: 'Tất cả bác sĩ',
      description: 'Tìm bác sĩ theo triệu chứng, tên bác sĩ hoặc khoa. Dùng bộ lọc nhanh để thu hẹp theo chuyên khoa, phí tư vấn và kinh nghiệm.',
      searchLabel: 'Tìm kiếm bác sĩ',
      searchPlaceholder: 'Nhập tên bác sĩ, khoa hoặc chuyên môn...',
      departmentLabel: 'Khoa',
      allDepartments: 'Tất cả khoa',
      feeLabel: 'Phí tư vấn',
      experienceLabel: 'Kinh nghiệm',
      resultCount: '{{visible}}/{{total}} bác sĩ',
      clearFilters: 'Xóa bộ lọc',
      loading: 'Đang tải danh sách bác sĩ...',
      error: 'Không thể tải danh sách bác sĩ.',
      emptyTitle: 'Không tìm thấy bác sĩ phù hợp',
      emptyDescription: 'Thử nhập triệu chứng khác hoặc xóa bộ lọc tìm kiếm.',
    },
    departmentsPage: {
      eyebrow: 'Khoa chuyên môn',
      title: 'Danh sách khoa',
      description: 'Xem toàn bộ khoa đang hoạt động và chọn bác sĩ phù hợp theo nhu cầu khám.',
      searchLabel: 'Tìm khoa',
      searchPlaceholder: 'Ví dụ: Tim mạch, Da liễu, Hô hấp...',
      loading: 'Đang tải danh sách khoa...',
      error: 'Không thể tải danh sách khoa.',
      emptyTitle: 'Không tìm thấy khoa phù hợp',
      emptyDescription: 'Thử nhập từ khóa khác hoặc xóa nội dung tìm kiếm.',
      fallbackDescription: 'Khoa đang tiếp nhận lịch khám trong hệ thống.',
      viewDetails: 'Xem chi tiết khoa',
      itemLabel: 'khoa',
    },
    departmentDetail: {
      back: 'Quay lại danh sách khoa',
      loading: 'Đang tải thông tin khoa...',
      error: 'Không thể tải thông tin khoa.',
      infoEyebrow: 'Thông tin khoa',
      fallbackDescription: 'Khoa đang tiếp nhận lịch khám và tư vấn trong hệ thống.',
      statusTitle: 'Trạng thái',
      activeStatus: 'Đang hoạt động và nhận lịch khám.',
      inactiveStatus: 'Hiện chưa nhận lịch khám.',
      doctorCount: '{{count}} bác sĩ trực thuộc',
      overviewTitle: 'Tổng quan',
      overviewFallback: 'Khoa đang tiếp nhận, thăm khám và điều trị các nhu cầu sức khỏe phù hợp trong hệ thống.',
      teamTitle: 'Đội ngũ chuyên môn',
      teamText: 'Khoa được vận hành bởi các bác sĩ đang hoạt động trong hệ thống, có hồ sơ chuyên môn và lịch khám được cập nhật để bệnh nhân dễ dàng lựa chọn.',
      bookingTitle: 'Đặt lịch',
      bookingText: 'Bệnh nhân có thể chọn bác sĩ trực thuộc khoa, xem lịch trống theo ngày và gửi yêu cầu đặt lịch ngay trên hệ thống.',
      doctorsEyebrow: 'Bác sĩ trực thuộc',
      viewDirectory: 'Xem trong danh bạ',
      emptyTitle: 'Chưa có bác sĩ trực thuộc khoa này',
      emptyDescription: 'Bạn có thể quay lại sau khi hệ thống cập nhật thêm hồ sơ bác sĩ.',
    },
    payment: {
      title: 'Thanh toán lịch khám',
      amount: 'Số tiền',
      paymentCode: 'Mã payment',
      appointmentCode: 'Mã lịch hẹn',
      transferContent: 'Nội dung chuyển khoản',
      pending: 'Đang chờ thanh toán',
      paid: 'Đã thanh toán',
      failed: 'Thanh toán thất bại',
      cancelled: 'Đã hủy',
      downloadInvoice: 'Tải hóa đơn PDF',
      downloading: 'Đang tải...',
      successToast: 'Thanh toán thành công. Lịch khám đã được xác nhận.',
      statusError: 'Không thể tải trạng thái thanh toán.',
      loadingQr: 'Đang tải mã QR thanh toán...',
      invoiceError: 'Không thể tải hóa đơn.',
      successEyebrow: 'Thanh toán thành công',
      successTitle: 'Lịch khám đã được xác nhận',
      doctorLabel: 'Bác sĩ',
      timeLabel: 'Thời gian khám',
      fallbackDoctor: 'Bác sĩ',
      updating: 'Đang cập nhật',
    },
  },
}

type LanguageContextValue = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, values?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

const isLanguage = (value: string | null): value is Language => {
  return value === 'en' || value === 'ja' || value === 'vi'
}

const getInitialLanguage = (): Language => {
  if (typeof window === 'undefined') return 'vi'

  const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY)
  if (isLanguage(storedLanguage)) return storedLanguage

  const browserLanguage = window.navigator.language.slice(0, 2)
  return isLanguage(browserLanguage) ? browserLanguage : 'vi'
}

const resolveTranslation = (language: Language, key: string) => {
  const segments = key.split('.')
  let current: TranslationValue | undefined = translations[language]

  for (const segment of segments) {
    if (!current || typeof current === 'string') return undefined
    current = current[segment]
  }

  return typeof current === 'string' ? current : undefined
}

const interpolate = (value: string, values?: Record<string, string | number>) => {
  if (!values) return value

  return Object.entries(values).reduce(
    (result, [name, replacement]) => result.replaceAll(`{{${name}}}`, String(replacement)),
    value,
  )
}

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage)

  useEffect(() => {
    document.documentElement.lang = language
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language)
  }, [language])

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage: setLanguageState,
      t: (key, values) => interpolate(resolveTranslation(language, key) ?? resolveTranslation('en', key) ?? key, values),
    }),
    [language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useTranslation = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useTranslation must be used within LanguageProvider')
  }

  return context
}
